// Code generated by mockery v2.36.0. DO NOT EDIT.

package dynamodb

import (
	expression "github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// BatchGetWithSort provides a mock function with given fields: values
func (_m *MockClient) BatchGetWithSort(values map[string]interface{}) error {
	ret := _m.Called(values)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOne provides a mock function with given fields: table, partitionKey, bindTo
func (_m *MockClient) GetOne(table string, partitionKey string, bindTo interface{}) error {
	ret := _m.Called(table, partitionKey, bindTo)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = rf(table, partitionKey, bindTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOneWithSort provides a mock function with given fields: table, partitionKey, sortKey, bindTo
func (_m *MockClient) GetOneWithSort(table string, partitionKey string, sortKey string, bindTo interface{}) error {
	ret := _m.Called(table, partitionKey, sortKey, bindTo)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, interface{}) error); ok {
		r0 = rf(table, partitionKey, sortKey, bindTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryExpression provides a mock function with given fields: table, query, pageSize, pageNumber, bindTo
func (_m *MockClient) QueryExpression(table string, query expression.Expression, pageSize int32, pageNumber int32, bindTo interface{}) error {
	ret := _m.Called(table, query, pageSize, pageNumber, bindTo)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, expression.Expression, int32, int32, interface{}) error); ok {
		r0 = rf(table, query, pageSize, pageNumber, bindTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryGSI provides a mock function with given fields: table, globalIndex, query, customLimit, pageDesired, bindTo
func (_m *MockClient) QueryGSI(table string, globalIndex string, query expression.Expression, customLimit int32, pageDesired int32, bindTo interface{}) error {
	ret := _m.Called(table, globalIndex, query, customLimit, pageDesired, bindTo)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, expression.Expression, int32, int32, interface{}) error); ok {
		r0 = rf(table, globalIndex, query, customLimit, pageDesired, bindTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryOne provides a mock function with given fields: table, partitionKey, limit, bindTo
func (_m *MockClient) QueryOne(table string, partitionKey string, limit int32, bindTo interface{}) error {
	ret := _m.Called(table, partitionKey, limit, bindTo)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int32, interface{}) error); ok {
		r0 = rf(table, partitionKey, limit, bindTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: table, item
func (_m *MockClient) Save(table string, item interface{}) error {
	ret := _m.Called(table, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(table, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
